Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tblUsers}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'S'
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Trips:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tblTrips}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'S'
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Tags:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tblTags}
      AttributeDefinitions:
        - AttributeName: pKey
          AttributeType: 'N'
        - AttributeName: nameLower
          AttributeType: 'S'
      KeySchema:
        - AttributeName: pKey
          KeyType: HASH
        - AttributeName: nameLower
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Countries:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tblCountries}
      AttributeDefinitions:
        - AttributeName: pKey
          AttributeType: 'N'
        - AttributeName: nameLower
          AttributeType: 'S'
      KeySchema:
        - AttributeName: pKey
          KeyType: HASH
        - AttributeName: nameLower
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Messages:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tblMessages}
      AttributeDefinitions:
        - AttributeName: toMemberId
          AttributeType: 'S'
        - AttributeName: sentOn
          AttributeType: 'N'
      KeySchema:
        - AttributeName: toMemberId
          KeyType: HASH
        - AttributeName: sentOn
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}

  Members:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.tblMembers}
      AttributeDefinitions:
        - AttributeName: memberId
          AttributeType: 'S'
        - AttributeName: tripId
          AttributeType: 'S'
      KeySchema:
        - AttributeName: memberId
          KeyType: HASH
        - AttributeName: tripId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
