service: tripsha-app-api

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-split-stacks
  - serverless-offline
custom:
  stage: ${opt:stage, self:provider.stage}
  customDomain:
    domainName: ${self:provider.stage}-api.tripsha.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'REGIONAL'
    websockets:
      domainName: ${self:provider.stage}-api.tripsha.com
      basePath: ''
      createRoute53Record: true
      endpointType: 'REGIONAL'
      stage: '${self:provider.stage}'

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  splitStacks:
    nestedStackCount: 20
    perFunction: false
    perType: false
    perGroupFunction: true

  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs8.10
  # stage: dev
  stage: staging
  # stage: prod-api
  region: us-east-1
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - 'execute-api:ManageConnections'
  #     Resource:
  #       - 'arn:aws:execute-api:*:*:**/@connections/*'
package:
  individually: true

functions:
  - ${file(src/routes/users/functions.yml)}
  - ${file(src/routes/trips/functions.yml)}
  - ${file(src/routes/trip-tags/functions.yml)}
  - ${file(src/routes/tags/functions.yml)}
  - ${file(src/routes/messages/functions.yml)}
  - ${file(src/routes/countries/functions.yml)}
  - ${file(src/routes/members/functions.yml)}
  - ${file(src/routes/seeds/functions.yml)}
  - ${file(src/routes/payments/functions.yml)}

resources:
  # API Gateway Errors
  - ${file(src/resources/api-gateway-errors.yml)}
  # S3
  - ${file(src/resources/s3-bucket.yml)}
  # Cognito
  - ${file(src/resources/cognito-user-pool.yml)}
  - ${file(src/resources/cognito-identity-pool.yml)}
