service: tripsha-app-api

plugins:
  - serverless-webpack 
  - serverless-aws-documentation
  - serverless-reqvalidator-plugin  
  - serverless-dynamodb-local
  - serverless-offline   

custom: 
  stage: ${opt:stage, self:provider.stage}

  dynamodb:
    start:
      migrate: true
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
  documentation: ${file(api-doc.yml):documentation}
  tbl_users: ${self:custom.stage}-users
  tbl_trips: ${self:custom.stage}-trips

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  environment: ${file(resources/env-variables.yml)}    

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ UsersTable, Arn ]
        - "Fn::GetAtt": [ TripsTable, Arn ]

functions:  
  - ${file(routes/users/functions.yml)}
  - ${file(routes/trips/functions.yml)}
         
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}