service: tripsha-app-api

plugins:
  - serverless-webpack
  - serverless-plugin-split-stacks
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-prune-plugin
  # - serverless-domain-manager
custom:
  stage: ${opt:stage, self:provider.stage}
  # customDomain:
  #   domainName: ${self:provider.stage}-api.tripsha.com
  #   basePath: ''
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true
  #   endpointType: 'REGIONAL'
  #   websockets:
  #     domainName: ${self:provider.stage}-api.tripsha.com
  #     basePath: ''
  #     createRoute53Record: true
  #     endpointType: 'REGIONAL'
  #     stage: '${self:provider.stage}'

  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  splitStacks:
    nestedStackCount: 20
    perFunction: true
    perType: false
    perGroupFunction: true

  # environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-067be5b7ef9f631a2
    subnetIds:
      - subnet-0803c091167df1253
      - subnet-0e171b9be6a40c7a2
      - subnet-09d52b9d017a45385
  environment:
    DB_CONN: ${file(./config/${self:custom.stage}.json):DB_CONN}
    MAILCHIMP_INSTANCE: ${file(./config/${self:custom.stage}.json):MAILCHIMP_INSTANCE}
    MAILCHIMP_API_KEY: ${file(./config/${self:custom.stage}.json):MAILCHIMP_API_KEY}
    MAILCHIMP_AUDIENCE_LIST_ID: ${file(./config/${self:custom.stage}.json):MAILCHIMP_AUDIENCE_LIST_ID}
    STRIPE_SECRET_KEY: ${file(./config/${self:custom.stage}.json):STRIPE_SECRET_KEY}
    CLIENT_BASE_URL: ${file(./config/${self:custom.stage}.json):CLIENT_BASE_URL}
    AIRTABLE_TOKEN: ${file(./config/${self:custom.stage}.json):AIRTABLE_TOKEN}
    INFURA_KEY: ${file(./config/${self:custom.stage}.json):INFURA_KEY}
    HOT_WALLET_KEY: ${file(./config/${self:custom.stage}.json):HOT_WALLET_KEY}
    LOCAL_RPC_URL: ${file(./config/${self:custom.stage}.json):LOCAL_RPC_URL}
    AWS_PROFILE: ${file(./config/${self:custom.stage}.json):AWS_PROFILE}
    ENV: ${self:custom.stage}
  iamRoleStatements:
    - Action:
        - 'cognito-idp:ListUsers'
        - 'cognito-idp:AdminCreateUser'
        - 'cognito-idp:AdminSetUserPassword'
        - 'cognito-idp:AdminEnableUser'
        - 'cognito-idp:AdminDisableUser'
        - 'cognito-idp:AdminUpdateUserAttributes'
        - 'cognito-idp:adminConfirmSignUp'
        - 'cognito-idp:adminGetUser'
      Resource:
        - 'arn:aws:cognito-idp:*'
      Effect: Allow
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'
    - Effect: 'Allow'
      Action:
        - 'ses:*'
      Resource: '*'

package:
  individually: false
  excludeDevDependencies: true
  exclude:
    - 'node_modules/**' # no need to add this yourself, this plugin does it for you
    - 'tests/**'
    - 'tests-integration/**'
    - '.idea/**'
    - 'serverless-configs/**'
    - 'envs/**'
    - 'support/**'
    - '.vscode/**'
    - '.api-doc-dist/**'
    - 'scripts/**'
    - '.git/**'
    - '.nyc_output'
    - 'tmp/**'
    - 'coverage/**'
    - 'package-lock.json'
    - 'yarn.lock'
    - 'vpc.json'
    - 'test-api-call.sh'
    - '.prettirrc'
    - '.eslintrc*'
    - 'test-api-call.sh'

functions:
  - ${file(src/routes/index.yml)}
  - ${file(src/routes/messages/functions.yml)}
  - ${file(src/schedules/trips/functions.yml)}
  - ${file(src/schedules/crypto/functions.yml)}

resources:
  # API Gateway Errors
  - ${file(src/resources/api-gateway-errors.yml)}
  # # S3
  - ${file(src/resources/s3-bucket.yml)}
  # Cognito
  - ${file(src/resources/cognito-user-pool.yml)}
  - ${file(src/resources/cognito-identity-pool.yml)}
