const serverless = require('serverless-http');
const express = require('express');
const cors = require('cors');
import { dbConnect } from '../utils';
import Countries from './countries';
import Tags from './tags';
import TripTags from './trip-tags';
import Trips from './trips';
import Activities from './activity-logs';
import HostRequests from './hosts';
import Approvals from './approvals';
import Bookings from './bookings';
import Members from './members';
import Messages from './messages';
import Migrations from './migrations';
import Payments from './payments';

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(async (req, res, next) => {
  await dbConnect(res);
  next();
});
app.use('/tags', Tags);
app.use('/countries', Countries);
app.use('/trip-tags', TripTags);
app.use('/trips', Trips);
app.use('/trips', Trips);
app.use('/activities', Activities);
app.use('/host-requests', HostRequests);
app.use('/approvals', Approvals);
app.use('/bookings', Bookings);
app.use('/members', Members);
app.use('/conversations', Messages);
app.use('/migrations', Migrations);
app.use('/payments', Payments);

export const handler = serverless(app);
