Resources:
  # NotesTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: ${self:custom.tbl_notes}
  #     AttributeDefinitions:
  #       - AttributeName: userId
  #         AttributeType: S
  #       - AttributeName: noteId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: userId
  #         KeyType: HASH
  #       - AttributeName: noteId
  #         KeyType: RANGE
  #     # Set the capacity based on the stage
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: ${self:custom.tableThroughput}
  #       WriteCapacityUnits: ${self:custom.tableThroughput}

  TripsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tbl_trips}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: tripId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: tripId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
