openapi: '3.0.0'
info:
  version: 'v1.0'
  title: Tripsha API documentation
  description: This is the complete API documentation for all of the APIs
  termsOfService: https://tripsha.com/terms/
  contact:
    name: Tripsha API Team
    email: madanesanjay@yahoo.com
    url: https://tripsha.com
servers:
  - url: https://staging-api.tripsha.com
