openapi: '3.0.0'
info:
  version: 'v1.0'
  title: Tripsha API documentation
  description: This is complete API documentation of all the API
  termsOfService: https://tripsha.com/terms/
  contact:
    name: Tripsha API Team
    email: madanesanjay@yahoo.com
    url: https://tripsha.com
servers:
  - url: https://toavs4nqf6.execute-api.us-east-1.amazonaws.com/dev
  - url: http://localhost:3000
