swagger: '2.0'
info:
  version: 'v1.0'
  title: Tripsha API documentation
  description: This is complete API documentation of all the API
  termsOfService: https://tripsha.com/terms/
  contact:
    name: Tripsha API team
    email: madanesanjay@yahoo.com
    url: https://tripsha.com
host: localhost:3000
# basePath: /dev
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json