name: Deploy to AWS API Gateway

on:
  push:
    branches:
      - master  # Set a branch to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '14.x'  # Set the version of Node.js

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build  # Run your build command

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Set your AWS region

    - name: Deploy to AWS API Gateway
      uses: aws-actions/amazon-api-gatewayv2-action@v1
      with:
        name: 'tripsha-prod'  # Set your API name
        protocol: 'REST'  # Set your API protocol
        credentials: ${{ secrets.AWS_CREDENTIALS }}  # Set your AWS credentials