name: Node CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test:unit
    - run: yarn test:integration
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - uses: akhileshns/heroku-deploy@v3.12.12 # This action deploys to Heroku
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "tripsha-api" # Replace with your Heroku app name
        heroku_email: "ryan@tripsha.com" # Replace with your Heroku email
